Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-1"

  config.vm.define "ubuntu-test" do |server|
    server.vm.box = "ubuntu-1"
    server.vm.hostname = "test"
    server.vm.network "public_network", dev: "wlp61s0"
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = 4096
    lv.cpus = 4
    lv.usb :bus => 2, :device => 13
  end

  config.vm.network :public_network, :dev => "virbr1",
      :mode => "bridge",
      :type => "bridge"

  config.vm.provision "shell",
                      inline: "sudo apt -y install python"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/android/playbook.yml"
    ansible.become = true
  end
end
