- hosts: all
  vars_files:
    - vars/main.yml

  pre_tasks:
  - name: update apt
    become: true
    apt: update_cache=yes name=git
    when: ansible_facts['os_family'] == 'Debian'

  - name: Install UDEV rules
    become: true
    git:
      repo: https://github.com/M0Rf30/android-udev-rules.git
      dest: /usr/local/src/android-udev-rules
    when: ansible_facts['os_family'] == 'Debian'

  - name: cp UDEV rules
    become: true
    file:
      src: /usr/local/src/android-udev-rules/51-android.rules
      dest: /etc/udev/rules.d/51-android.rules
      mode: "a+r"
      state: link
    when: ansible_facts['os_family'] == 'Debian'

  - name: Install expect
    homebrew:
      name: expect
    when: ansible_facts['os_family'] == 'Darwin'

  roles:
    - role: ansible-role-android-sdk
      become: true

